// <auto-generated />
using System;
using ClassRoom.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClassRoom.Persistence.Migrations
{
    [DbContext(typeof(ClassRoomContext))]
    [Migration("20220919190841_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ClassRoom.Domain.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlocoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProfessor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("ClassRoom.Domain.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusBloco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blocos");
                });

            modelBuilder.Entity("ClassRoom.Domain.Aula", b =>
                {
                    b.HasOne("ClassRoom.Domain.Bloco", "Bloco")
                        .WithMany("Aulas")
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bloco");
                });

            modelBuilder.Entity("ClassRoom.Domain.Bloco", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
